# Generated by Django 2.0.1 on 2018-07-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20180705_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parâmetro NF-e'), ('ver_dashboard', 'Pode acessar o dashboard '), ('permissao3', 'Permissao 3'))},
        ),
    ]
